-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Untuk fitur Profile)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  role text default 'Anggota', -- 'Ketua', 'Pengurus', 'Anggota'
  phone text,
  constraint username_length check (char_length(full_name) >= 3)
);

-- 2. EVENTS (Untuk fitur Event)
create table events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  event_date timestamp with time zone not null, -- Menggabungkan date & time
  status text check (status in ('upcoming', 'ongoing', 'completed')) default 'upcoming',
  location text
);

-- 3. BILLS (Untuk fitur Finance)
create table bills (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  amount numeric not null,
  due_date timestamp with time zone not null,
  is_paid boolean default false
);

-- 4. NEWS (Untuk fitur Berita di Home)
create table news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  image_url text,
  author text,
  category text default 'News'
);

-- 5. ANNOUNCEMENTS (Untuk fitur Pengumuman di Home)
create table announcements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  badge_text text default 'Penting'
);

-- 6. ASPIRATIONS (Untuk fitur Pojok Kampung)
create table aspirations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  author text not null,
  content text not null,
  status text default 'Menunggu Tindak Lanjut'
);

-- 7. POLLING (Untuk fitur Polling)
create table pollings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  is_active boolean default true
);

create table polling_options (
  id bigint generated by default as identity primary key,
  polling_id bigint references pollings(id) on delete cascade not null,
  label text not null,
  vote_count integer default 0
);

-- SEED DATA (Data Awal)

-- Events
insert into events (title, description, event_date, status, location) values
('Kerja Bakti Lingkungan', 'Kegiatan kerja bakti membersihkan selokan dan lingkungan sekitar RT 03.', '2026-01-20 08:00:00+00', 'upcoming', 'RT 03'),
('Rapat Koordinasi Bulanan', 'Rapat koordinasi pengurus karang taruna untuk evaluasi kegiatan bulan ini.', '2026-01-25 19:30:00+00', 'upcoming', 'Balai RW'),
('Pelatihan Keterampilan Digital', 'Pelatihan dasar desain grafis dan pengelolaan media sosial untuk pemuda.', '2026-01-18 09:00:00+00', 'ongoing', 'Aula Kelurahan'),
('Lomba Kebersihan Lingkungan', 'Penilaian lomba kebersihan lingkungan antar RT yang telah selesai dilaksanakan.', '2025-12-30 16:00:00+00', 'completed', 'Lingkungan RW'),
('Donor Darah', 'Kegiatan donor darah bekerja sama dengan PMI di balai RW 05.', '2025-11-15 08:30:00+00', 'completed', 'Balai RW 05');

-- Bills
insert into bills (title, description, amount, due_date) values
('Iuran Kas Bulanan', 'Iuran kas karang taruna bulan Januari 2026.', 50000, '2026-01-25 00:00:00+00'),
('Iuran Kegiatan', 'Iuran untuk kegiatan kerja bakti lingkungan RW 05.', 30000, '2026-01-30 00:00:00+00');

-- News
insert into news (title, content, author, category, image_url) values
('Halo Dunia lorem ipsum', 'lorem ipsum dolor sit amet consectetur adipiscing elit...', 'Ketua', 'News', 'https://picsum.photos/400/300'),
('Kegiatan Pemuda', 'Berita tentang kegiatan pemuda minggu ini...', 'Sekretaris', 'News', 'https://picsum.photos/400/301');

-- Announcements
insert into announcements (title, description, badge_text) values
('Bank Sampah', 'Tanggal 18 januari 2026 ada kegiatan bank sampah', 'Penting'),
('Rapat Pleno', 'Diharapkan kehadiran seluruh anggota', 'Wajib');

-- Aspirations
insert into aspirations (author, content, status) values
('Budi', 'Mohon dipertimbangkan penambahan lampu jalan di RT 03.', 'Menunggu Tindak Lanjut'),
('Siti', 'Usul diadakan kegiatan pelatihan keterampilan digital.', 'Sedang Ditinjau');

-- Pollings
insert into pollings (title) values ('Kegiatan apa yang kamu pilih minggu ini?');
insert into polling_options (polling_id, label, vote_count) 
select id, 'Kerja bakti lingkungan', 40 from pollings where title = 'Kegiatan apa yang kamu pilih minggu ini?';
insert into polling_options (polling_id, label, vote_count) 
select id, 'Pelatihan keterampilan', 25 from pollings where title = 'Kegiatan apa yang kamu pilih minggu ini?';
insert into polling_options (polling_id, label, vote_count) 
select id, 'Lomba olahraga', 35 from pollings where title = 'Kegiatan apa yang kamu pilih minggu ini?';
