// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQtAqCbt-Cf9aW_vEI3hmhJb0l8R8g7M',
    appId: '1:227195299034:web:115ff7b3df9a835fb071e3',
    messagingSenderId: '227195299034',
    projectId: 'karangtaruna-82460',
    authDomain: 'karangtaruna-82460.firebaseapp.com',
    storageBucket: 'karangtaruna-82460.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgo9ZZAfG93ufaRGkNjvw6Tv7VvGh0ofQ',
    appId: '1:227195299034:android:c5c5f163b3cb6f0eb071e3',
    messagingSenderId: '227195299034',
    projectId: 'karangtaruna-82460',
    storageBucket: 'karangtaruna-82460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lT5dZyBRALGc_m0RKXzlTuzqfd3p5NA',
    appId: '1:227195299034:ios:f5b5a5ef1118cf58b071e3',
    messagingSenderId: '227195299034',
    projectId: 'karangtaruna-82460',
    storageBucket: 'karangtaruna-82460.firebasestorage.app',
    iosBundleId: 'com.example.karangTaruna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lT5dZyBRALGc_m0RKXzlTuzqfd3p5NA',
    appId: '1:227195299034:ios:f5b5a5ef1118cf58b071e3',
    messagingSenderId: '227195299034',
    projectId: 'karangtaruna-82460',
    storageBucket: 'karangtaruna-82460.firebasestorage.app',
    iosBundleId: 'com.example.karangTaruna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZQtAqCbt-Cf9aW_vEI3hmhJb0l8R8g7M',
    appId: '1:227195299034:web:03840ccd4329b0e7b071e3',
    messagingSenderId: '227195299034',
    projectId: 'karangtaruna-82460',
    authDomain: 'karangtaruna-82460.firebaseapp.com',
    storageBucket: 'karangtaruna-82460.firebasestorage.app',
  );

}
