-- Create finance_accounts table
CREATE TABLE IF NOT EXISTS finance_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT, -- Material icon name
  color TEXT, -- Hex color string
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create finance_transactions table
CREATE TABLE IF NOT EXISTS finance_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT REFERENCES finance_accounts(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  amount BIGINT NOT NULL, -- Always positive
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  description TEXT,
  transaction_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default accounts if they don't exist
INSERT INTO finance_accounts (name, description, icon, color)
SELECT 'Kas Organisasi', 'Dana operasional utama organisasi', 'account_balance', '0xFF00BA9B'
WHERE NOT EXISTS (SELECT 1 FROM finance_accounts WHERE name = 'Kas Organisasi');

INSERT INTO finance_accounts (name, description, icon, color)
SELECT 'Kas Olahraga', 'Dana untuk kegiatan olahraga', 'sports_soccer', '0xFFFFA726'
WHERE NOT EXISTS (SELECT 1 FROM finance_accounts WHERE name = 'Kas Olahraga');

INSERT INTO finance_accounts (name, description, icon, color)
SELECT 'Kas Sosial', 'Dana untuk kegiatan sosial', 'people', '0xFFEF5350'
WHERE NOT EXISTS (SELECT 1 FROM finance_accounts WHERE name = 'Kas Sosial');

-- Enable RLS (Row Level Security)
ALTER TABLE finance_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_transactions ENABLE ROW LEVEL SECURITY;

-- Policies for finance_accounts (Everyone can view, Admin can manage)
CREATE POLICY "Everyone can view finance accounts" ON finance_accounts
  FOR SELECT USING (true);

CREATE POLICY "Admins can insert finance accounts" ON finance_accounts
  FOR INSERT WITH CHECK (
  auth.uid() IN (SELECT id FROM profiles WHERE role = 'Admin')
);

CREATE POLICY "Admins can update finance accounts" ON finance_accounts
  FOR UPDATE USING (
  auth.uid() IN (SELECT id FROM profiles WHERE role = 'Admin')
);

CREATE POLICY "Admins can delete finance accounts" ON finance_accounts
  FOR DELETE USING (
  auth.uid() IN (SELECT id FROM profiles WHERE role = 'Admin')
);

-- Policies for finance_transactions (Everyone can view, Admin/Bendahara can manage)
CREATE POLICY "Everyone can view finance transactions" ON finance_transactions
  FOR SELECT USING (true);

CREATE POLICY "Admins and Bendahara can insert finance transactions" ON finance_transactions
  FOR INSERT WITH CHECK (
  auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Bendahara'))
);

CREATE POLICY "Admins and Bendahara can update finance transactions" ON finance_transactions
  FOR UPDATE USING (
  auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Bendahara'))
);

CREATE POLICY "Admins and Bendahara can delete finance transactions" ON finance_transactions
  FOR DELETE USING (
  auth.uid() IN (SELECT id FROM profiles WHERE role IN ('Admin', 'Bendahara'))
);
